import 'package:flutter/material.dart';

// Extension to easily access translations from any widget
extension TranslationExtension on BuildContext {
  String translate(String key) {
    final languageProvider = LanguageProvider.of(this);
    final locale = languageProvider?.locale ?? const Locale('en', 'US');
    return AppLanguages.translate(key, locale);
  }
}

class LanguageProvider extends InheritedWidget {
  final Locale locale;
  final Function(Locale) changeLanguage;

  const LanguageProvider({
    super.key,
    required this.locale,
    required this.changeLanguage,
    required super.child,
  });

  static LanguageProvider? of(BuildContext context) {
    return context.dependOnInheritedWidgetOfExactType<LanguageProvider>();
  }

  @override
  bool updateShouldNotify(LanguageProvider oldWidget) {
    return locale != oldWidget.locale;
  }
}

// Language mapping
class AppLanguages {
  static const Map<String, Locale> languageMap = {
    'English (US)': Locale('en', 'US'),
    'English (UK)': Locale('en', 'GB'),
    'Arabic': Locale('ar'),
    'French': Locale('fr'),
    'Spanish': Locale('es'),
    'German': Locale('de'),
    'Italian': Locale('it'),
    'Portuguese': Locale('pt'),
    'Bengali': Locale('bn'),
    'Russian': Locale('ru'),
    'Japanese': Locale('ja'),
    'Korean': Locale('ko'),
    'Indonesian': Locale('id'),
    'Turkish': Locale('tr'),
    'Hindi': Locale('hi'),
    'Urdu': Locale('ur'),
    'Polish': Locale('pl'),
    'Dutch': Locale('nl'),
    'Greek': Locale('el'),
    'Swedish': Locale('sv'),
    'Norwegian': Locale('no'),
    'Danish': Locale('da'),
    'Finnish': Locale('fi'),
    'Czech': Locale('cs'),
    'Romanian': Locale('ro'),
    'Hungarian': Locale('hu'),
    'Thai': Locale('th'),
    'Vietnamese': Locale('vi'),
    'Hebrew': Locale('he'),
    'Persian': Locale('fa'),
    'Malay': Locale('ms'),
    'Tagalog': Locale('tl'),
    'Swahili': Locale('sw'),
    'Mandarin': Locale('zh', 'CN'),
  };

  static Locale getLocaleFromLanguageName(String languageName) {
    return languageMap[languageName] ?? const Locale('en', 'US');
  }

  static String getLanguageNameFromLocale(Locale locale) {
    for (var entry in languageMap.entries) {
      if (entry.value.languageCode == locale.languageCode) {
        if (locale.countryCode != null) {
          if (entry.value.countryCode == locale.countryCode) {
            return entry.key;
          }
        } else {
          return entry.key;
        }
      }
    }
    return 'English (US)';
  }

  // Get translated language name based on current locale
  static String getTranslatedLanguageName(String languageName, Locale locale) {
    final translations = _getLanguageTranslations(locale);
    return translations[languageName] ?? languageName;
  }

  // Language name translations for all supported languages
  static Map<String, Map<String, String>> _languageTranslations = {
    'en': {
      'English (US)': 'English (US)',
      'English (UK)': 'English (UK)',
      'Arabic': 'Arabic',
      'French': 'French',
      'Spanish': 'Spanish',
      'German': 'German',
      'Italian': 'Italian',
      'Portuguese': 'Portuguese',
      'Bengali': 'Bengali',
      'Russian': 'Russian',
      'Japanese': 'Japanese',
      'Korean': 'Korean',
      'Indonesian': 'Indonesian',
      'Turkish': 'Turkish',
      'Hindi': 'Hindi',
      'Urdu': 'Urdu',
      'Polish': 'Polish',
      'Dutch': 'Dutch',
      'Greek': 'Greek',
      'Swedish': 'Swedish',
      'Norwegian': 'Norwegian',
      'Danish': 'Danish',
      'Finnish': 'Finnish',
      'Czech': 'Czech',
      'Romanian': 'Romanian',
      'Hungarian': 'Hungarian',
      'Thai': 'Thai',
      'Vietnamese': 'Vietnamese',
      'Hebrew': 'Hebrew',
      'Persian': 'Persian',
      'Malay': 'Malay',
      'Tagalog': 'Tagalog',
      'Swahili': 'Swahili',
      'Mandarin': 'Mandarin',
    },
    'ar': {
      'English (US)': 'الإنجليزية (أمريكا)',
      'English (UK)': 'الإنجليزية (بريطانيا)',
      'Arabic': 'العربية',
      'French': 'الفرنسية',
      'Spanish': 'الإسبانية',
      'German': 'الألمانية',
      'Italian': 'الإيطالية',
      'Portuguese': 'البرتغالية',
      'Bengali': 'البنغالية',
      'Russian': 'الروسية',
      'Japanese': 'اليابانية',
      'Korean': 'الكورية',
      'Indonesian': 'الإندونيسية',
      'Turkish': 'التركية',
      'Hindi': 'الهندية',
      'Urdu': 'الأردية',
      'Polish': 'البولندية',
      'Dutch': 'الهولندية',
      'Greek': 'اليونانية',
      'Swedish': 'السويدية',
      'Norwegian': 'النرويجية',
      'Danish': 'الدنماركية',
      'Finnish': 'الفنلندية',
      'Czech': 'التشيكية',
      'Romanian': 'الرومانية',
      'Hungarian': 'المجرية',
      'Thai': 'التايلاندية',
      'Vietnamese': 'الفيتنامية',
      'Hebrew': 'العبرية',
      'Persian': 'الفارسية',
      'Malay': 'الماليزية',
      'Tagalog': 'التاغالوغية',
      'Swahili': 'السواحيلية',
      'Mandarin': 'المندرينية',
    },
    'fr': {
      'English (US)': 'Anglais (États-Unis)',
      'English (UK)': 'Anglais (Royaume-Uni)',
      'Arabic': 'Arabe',
      'French': 'Français',
      'Spanish': 'Espagnol',
      'German': 'Allemand',
      'Italian': 'Italien',
      'Portuguese': 'Portugais',
      'Bengali': 'Bengali',
      'Russian': 'Russe',
      'Japanese': 'Japonais',
      'Korean': 'Coréen',
      'Indonesian': 'Indonésien',
      'Turkish': 'Turc',
      'Hindi': 'Hindi',
      'Urdu': 'Ourdou',
      'Polish': 'Polonais',
      'Dutch': 'Néerlandais',
      'Greek': 'Grec',
      'Swedish': 'Suédois',
      'Norwegian': 'Norvégien',
      'Danish': 'Danois',
      'Finnish': 'Finnois',
      'Czech': 'Tchèque',
      'Romanian': 'Roumain',
      'Hungarian': 'Hongrois',
      'Thai': 'Thaï',
      'Vietnamese': 'Vietnamien',
      'Hebrew': 'Hébreu',
      'Persian': 'Persan',
      'Malay': 'Malais',
      'Tagalog': 'Tagalog',
      'Swahili': 'Swahili',
      'Mandarin': 'Mandarin',
    },
    'es': {
      'English (US)': 'Inglés (EE. UU.)',
      'English (UK)': 'Inglés (Reino Unido)',
      'Arabic': 'Árabe',
      'French': 'Francés',
      'Spanish': 'Español',
      'German': 'Alemán',
      'Italian': 'Italiano',
      'Portuguese': 'Portugués',
      'Bengali': 'Bengalí',
      'Russian': 'Ruso',
      'Japanese': 'Japonés',
      'Korean': 'Coreano',
      'Indonesian': 'Indonesio',
      'Turkish': 'Turco',
      'Hindi': 'Hindi',
      'Urdu': 'Urdu',
      'Polish': 'Polaco',
      'Dutch': 'Neerlandés',
      'Greek': 'Griego',
      'Swedish': 'Sueco',
      'Norwegian': 'Noruego',
      'Danish': 'Danés',
      'Finnish': 'Finlandés',
      'Czech': 'Checo',
      'Romanian': 'Rumano',
      'Hungarian': 'Húngaro',
      'Thai': 'Tailandés',
      'Vietnamese': 'Vietnamita',
      'Hebrew': 'Hebreo',
      'Persian': 'Persa',
      'Malay': 'Malayo',
      'Tagalog': 'Tagalo',
      'Swahili': 'Suajili',
      'Mandarin': 'Mandarín',
    },
    'de': {
      'English (US)': 'Englisch (USA)',
      'English (UK)': 'Englisch (UK)',
      'Arabic': 'Arabisch',
      'French': 'Französisch',
      'Spanish': 'Spanisch',
      'German': 'Deutsch',
      'Italian': 'Italienisch',
      'Portuguese': 'Portugiesisch',
      'Bengali': 'Bengalisch',
      'Russian': 'Russisch',
      'Japanese': 'Japanisch',
      'Korean': 'Koreanisch',
      'Indonesian': 'Indonesisch',
      'Turkish': 'Türkisch',
      'Hindi': 'Hindi',
      'Urdu': 'Urdu',
      'Polish': 'Polnisch',
      'Dutch': 'Niederländisch',
      'Greek': 'Griechisch',
      'Swedish': 'Schwedisch',
      'Norwegian': 'Norwegisch',
      'Danish': 'Dänisch',
      'Finnish': 'Finnisch',
      'Czech': 'Tschechisch',
      'Romanian': 'Rumänisch',
      'Hungarian': 'Ungarisch',
      'Thai': 'Thailändisch',
      'Vietnamese': 'Vietnamesisch',
      'Hebrew': 'Hebräisch',
      'Persian': 'Persisch',
      'Malay': 'Malaiisch',
      'Tagalog': 'Tagalog',
      'Swahili': 'Suaheli',
      'Mandarin': 'Mandarin',
    },
    'it': {
      'English (US)': 'Inglese (USA)',
      'English (UK)': 'Inglese (Regno Unito)',
      'Arabic': 'Arabo',
      'French': 'Francese',
      'Spanish': 'Spagnolo',
      'German': 'Tedesco',
      'Italian': 'Italiano',
      'Portuguese': 'Portoghese',
      'Bengali': 'Bengalese',
      'Russian': 'Russo',
      'Japanese': 'Giapponese',
      'Korean': 'Coreano',
      'Indonesian': 'Indonesiano',
      'Turkish': 'Turco',
      'Hindi': 'Hindi',
      'Urdu': 'Urdu',
      'Polish': 'Polacco',
      'Dutch': 'Olandese',
      'Greek': 'Greco',
      'Swedish': 'Svedese',
      'Norwegian': 'Norvegese',
      'Danish': 'Danese',
      'Finnish': 'Finlandese',
      'Czech': 'Ceco',
      'Romanian': 'Rumeno',
      'Hungarian': 'Ungherese',
      'Thai': 'Tailandese',
      'Vietnamese': 'Vietnamita',
      'Hebrew': 'Ebraico',
      'Persian': 'Persiano',
      'Malay': 'Malese',
      'Tagalog': 'Tagalog',
      'Swahili': 'Swahili',
      'Mandarin': 'Mandarino',
    },
  };

  static Map<String, String> _getLanguageTranslations(Locale locale) {
    return _languageTranslations[locale.languageCode] ??
        _languageTranslations['en']!;
  }

  // Central translation system for the entire app
  static String translate(String key, Locale locale) {
    final translations =
        _appTranslations[locale.languageCode] ?? _appTranslations['en']!;
    return translations[key] ?? key;
  }

  // App-wide translations
  static final Map<String, Map<String, String>> _appTranslations = {
    'en': {
      // Common
      'RaknaGo': 'RaknaGo',
      'Cancel': 'Cancel',
      'Save': 'Save',
      'Delete': 'Delete',
      'Edit': 'Edit',
      'Confirm': 'Confirm',
      'Yes': 'Yes',
      'No': 'No',
      'OK': 'OK',
      'Close': 'Close',
      'Back': 'Back',
      'Next': 'Next',
      'Continue': 'Continue',
      'Done': 'Done',
      'Search': 'Search',
      'Loading': 'Loading',
      'Error': 'Error',
      'Success': 'Success',
      'Warning': 'Warning',
      'User': 'User',
      'No phone number': 'No phone number',

      // Navigation & Screens
      'Home': 'Home',
      'Account': 'Account',
      'Wallet': 'Wallet',
      'Bookings': 'Bookings',
      'Saved': 'Saved',
      'Settings': 'Settings',
      'Language': 'Language',
      'Personal Info': 'Personal Info',
      'Security': 'Security',
      'Payment Methods': 'Payment Methods',
      'Help Center': 'Help Center',
      'About': 'About',
      'Privacy Policy': 'Privacy Policy',
      'Top Up Wallet': 'Top Up Wallet',
      'Scan QR Code': 'Scan QR Code',
      'Please point the camera at the QR Code':
          'Please point the camera at the QR Code',

      // Language Screen
      'Suggested': 'Suggested',
      'All Languages': 'All Languages',
      'Language changed to': 'Language changed to',

      // Common Actions
      'Logout': 'Logout',
      'Login': 'Login',
      'Sign Up': 'Sign Up',
      'View': 'View',
      'Book': 'Book',
      'Cancel Booking': 'Cancel Booking',
      'View Details': 'View Details',
      'Dark Mode': 'Dark Mode',
      'About ParkSpot': 'About ParkSpot',
      'Logout Confirmation': 'Logout Confirmation',
      'Are you sure you want to logout?': 'Are you sure you want to logout?',
      'Yes, Logout': 'Yes, Logout',
      'My Wallet': 'My Wallet',
      'My Booking': 'My Booking',
      'Completed': 'Completed',
      'Canceled': 'Canceled',
      'Enter the amount of top up': 'Enter the amount of top up',
      'Processing, please wait...': 'Processing, please wait...',
      'QR Code:': 'QR Code:',
      'Location not available': 'Location not available',
      'Booking not found': 'Booking not found',
      'You can only cancel your own bookings':
          'You can only cancel your own bookings',
      'Invalid booking: Missing ID': 'Invalid booking: Missing ID',
      'Please log in to cancel bookings': 'Please log in to cancel bookings',
      'Error verifying booking:': 'Error verifying booking:',
      'No completed bookings': 'No completed bookings',
      'No canceled bookings': 'No canceled bookings',
      'No bookings': 'No bookings',
      'Search Bookings': 'Search Bookings',
      'Tesla (Plug)': 'Tesla (Plug)',
      'Max power': 'Max power',
      'Parked For': 'Parked For',
      'Duration': 'Duration',
      'Total Paid': 'Total Paid',
      'Amount': 'Amount',
      'Extra:': 'Extra:',
      'Available': 'Available',
      'In Use': 'In Use',
      'Unavailable': 'Unavailable',
      'Book Now': 'Book Now',
      'Full': 'Full',
      'Search station': 'Search station',
    },
    'ar': {
      'RaknaGo': 'راكناجو',
      // Common
      'Cancel': 'إلغاء',
      'Save': 'حفظ',
      'Delete': 'حذف',
      'Edit': 'تعديل',
      'Confirm': 'تأكيد',
      'Yes': 'نعم',
      'No': 'لا',
      'OK': 'موافق',
      'Close': 'إغلاق',
      'Back': 'رجوع',
      'Next': 'التالي',
      'Continue': 'متابعة',
      'Done': 'تم',
      'Search': 'بحث',
      'Loading': 'جاري التحميل',
      'Error': 'خطأ',
      'Success': 'نجح',
      'Warning': 'تحذير',
      'User': 'المستخدم',
      'No phone number': 'لا يوجد رقم هاتف',

      // Navigation & Screens
      'Home': 'الرئيسية',
      'Account': 'الحساب',
      'Wallet': 'المحفظة',
      'Bookings': 'الحجوزات',
      'Saved': 'المحفوظات',
      'Settings': 'الإعدادات',
      'Language': 'اللغة',
      'Personal Info': 'المعلومات الشخصية',
      'Security': 'الأمان',
      'Payment Methods': 'طرق الدفع',
      'Help Center': 'مركز المساعدة',
      'About': 'حول',
      'Privacy Policy': 'سياسة الخصوصية',
      'Top Up Wallet': 'شحن المحفظة',
      'Scan QR Code': 'مسح رمز QR',
      'Please point the camera at the QR Code':
          'يرجى توجيه الكاميرا إلى رمز QR',

      // Language Screen
      'Suggested': 'مقترح',
      'All Languages': 'جميع اللغات',
      'Language changed to': 'تم تغيير اللغة إلى',

      // Common Actions
      'Logout': 'تسجيل الخروج',
      'Login': 'تسجيل الدخول',
      'Sign Up': 'إنشاء حساب',
      'View': 'عرض',
      'Book': 'حجز',
      'Cancel Booking': 'إلغاء الحجز',
      'View Details': 'عرض التفاصيل',
      'Dark Mode': 'الوضع الداكن',
      'About ParkSpot': 'حول ParkSpot',
      'Logout Confirmation': 'تأكيد تسجيل الخروج',
      'Are you sure you want to logout?': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
      'Yes, Logout': 'نعم، تسجيل الخروج',
      'My Wallet': 'محفظتي',
      'My Booking': 'حجوزاتي',
      'Completed': 'مكتملة',
      'Canceled': 'ملغاة',
      'Enter the amount of top up': 'أدخل مبلغ الشحن',
      'Processing, please wait...': 'جاري المعالجة، يرجى الانتظار...',
      'QR Code:': 'رمز QR:',
      'Location not available': 'الموقع غير متاح',
      'Booking not found': 'الحجز غير موجود',
      'You can only cancel your own bookings': 'يمكنك إلغاء حجوزاتك فقط',
      'Invalid booking: Missing ID': 'حجز غير صالح: معرف مفقود',
      'Please log in to cancel bookings': 'يرجى تسجيل الدخول لإلغاء الحجوزات',
      'Error verifying booking:': 'خطأ في التحقق من الحجز:',
      'No completed bookings': 'لا توجد حجوزات مكتملة',
      'No canceled bookings': 'لا توجد حجوزات ملغاة',
      'No bookings': 'لا توجد حجوزات',
      'Search Bookings': 'بحث في الحجوزات',
      'Tesla (Plug)': 'تيسلا (قابس)',
      'Max power': 'الطاقة القصوى',
      'Parked For': 'مدة الوقوف',
      'Duration': 'المدة',
      'Total Paid': 'المبلغ المدفوع',
      'Amount': 'المبلغ',
      'Extra:': 'إضافي:',
      'Available': 'متاح',
      'In Use': 'قيد الاستخدام',
      'Unavailable': 'غير متاح',
      'Book Now': 'احجز الآن',
      'Full': 'ممتلئ',
      'Search station': 'ابحث عن محطة',
      'Name': 'الاسم',
      'Phone': 'الهاتف',
      'Email': 'البريد الإلكتروني',
      'Address': 'العنوان',
      'Date of Birth': 'تاريخ الميلاد',
      'Update': 'تحديث',
      'Change Password': 'تغيير كلمة المرور',
      'Current Password': 'كلمة المرور الحالية',
      'New Password': 'كلمة المرور الجديدة',
      'Confirm Password': 'تأكيد كلمة المرور',
      'Biometric Authentication': 'المصادقة البيومترية',
      'Face ID': 'Face ID',
      'Remember Me': 'تذكرني',
      'Continue with Google': 'المتابعة مع Google',
      'Full Name': 'الاسم الكامل',
      'Email Address': 'عنوان البريد الإلكتروني',
      'Password': 'كلمة المرور',
      'Account created successfully!': 'تم إنشاء الحساب بنجاح!',
      'Please agree to the terms and conditions':
          'يرجى الموافقة على الشروط والأحكام',
      'Let\'s you in': 'مرحباً بك',
      'or': 'أو',
      'Don\'t have an account?': 'ليس لديك حساب؟',
      'Already have an account?': 'لديك حساب بالفعل؟',
      'Create Account': 'إنشاء حساب',
      'Terms and Conditions': 'الشروط والأحكام',
      'I agree to the': 'أوافق على',
      'Create your account': 'إنشاء حسابك',
      'Sign up to get started': 'سجل للبدء',
      'Sign In': 'تسجيل الدخول',
      'No Saved Parkings': 'لا توجد مواقف محفوظة',
      'Save your favorite parking spots\nfor quick access':
          'احفظ مواقفك المفضلة\nللوصول السريع',
      'spots': 'أماكن',
      'reviews': 'تقييمات',
      'chargers': 'شواحن',
      'Search Saved': 'بحث في المحفوظات',
      'Recent Transactions': 'المعاملات الأخيرة',
      'View All': 'عرض الكل',
      'No transactions yet': 'لا توجد معاملات بعد',
      'Your balance': 'رصيدك',
      'Top Up': 'شحن',
      'RaknaGo Card': 'بطاقة RaknaGo',
      'This booking is already completed. Are you sure you want to cancel it?':
          'هذا الحجز مكتمل بالفعل. هل أنت متأكد أنك تريد إلغاءه؟',
      'Are you sure you want to cancel this booking?':
          'هل أنت متأكد أنك تريد إلغاء هذا الحجز؟',
      'Time spent:': 'الوقت المستغرق:',
      'hours': 'ساعات',
      '1st hour (paid):': 'الساعة الأولى (مدفوعة):',
      'Total charge:': 'إجمالي الرسوم:',
      'Extra charge:': 'رسوم إضافية:',
      'Will be deducted from wallet': 'سيتم خصمها من المحفظة',
      'No additional charge': 'لا توجد رسوم إضافية',
      'First hour already paid (non-refundable)':
          'الساعة الأولى مدفوعة مسبقاً (غير قابلة للاسترداد)',
      'Yes, Cancel': 'نعم، إلغاء',
    },
    'fr': {
      'RaknaGo': 'RaknaGo',
      // Common
      'Cancel': 'Annuler',
      'Save': 'Enregistrer',
      'Delete': 'Supprimer',
      'Edit': 'Modifier',
      'Confirm': 'Confirmer',
      'Yes': 'Oui',
      'No': 'Non',
      'OK': 'OK',
      'Close': 'Fermer',
      'Back': 'Retour',
      'Next': 'Suivant',
      'Continue': 'Continuer',
      'Done': 'Terminé',
      'Search': 'Rechercher',
      'Loading': 'Chargement',
      'Error': 'Erreur',
      'Success': 'Succès',
      'Warning': 'Avertissement',
      'User': 'Utilisateur',
      'No phone number': 'Aucun numéro de téléphone',

      // Navigation & Screens
      'Home': 'Accueil',
      'Account': 'Compte',
      'Wallet': 'Portefeuille',
      'Bookings': 'Réservations',
      'Saved': 'Enregistrés',
      'Settings': 'Paramètres',
      'Language': 'Langue',
      'Personal Info': 'Informations personnelles',
      'Security': 'Sécurité',
      'Payment Methods': 'Méthodes de paiement',
      'Help Center': 'Centre d\'aide',
      'About': 'À propos',
      'Privacy Policy': 'Politique de confidentialité',
      'Top Up Wallet': 'Recharger le portefeuille',
      'Scan QR Code': 'Scanner le code QR',
      'Please point the camera at the QR Code':
          'Veuillez pointer la caméra vers le code QR',

      // Language Screen
      'Suggested': 'Suggéré',
      'All Languages': 'Toutes les langues',
      'Language changed to': 'Langue changée en',

      // Common Actions
      'Logout': 'Déconnexion',
      'Login': 'Connexion',
      'Sign Up': 'S\'inscrire',
      'View': 'Voir',
      'Book': 'Réserver',
      'Cancel Booking': 'Annuler la réservation',
      'View Details': 'Voir les détails',
      'Dark Mode': 'Mode sombre',
      'About ParkSpot': 'À propos de ParkSpot',
      'Logout Confirmation': 'Confirmation de déconnexion',
      'Are you sure you want to logout?':
          'Êtes-vous sûr de vouloir vous déconnecter ?',
      'Yes, Logout': 'Oui, se déconnecter',
      'My Wallet': 'Mon portefeuille',
      'My Booking': 'Mes réservations',
      'Completed': 'Terminé',
      'Canceled': 'Annulé',
      'Enter the amount of top up': 'Entrez le montant du rechargement',
      'Processing, please wait...':
          'Traitement en cours, veuillez patienter...',
      'QR Code:': 'Code QR:',
      'Location not available': 'Emplacement non disponible',
      'Booking not found': 'Réservation introuvable',
      'You can only cancel your own bookings':
          'Vous ne pouvez annuler que vos propres réservations',
      'Invalid booking: Missing ID': 'Réservation invalide: ID manquant',
      'Please log in to cancel bookings':
          'Veuillez vous connecter pour annuler les réservations',
      'Error verifying booking:':
          'Erreur lors de la vérification de la réservation:',
      'No completed bookings': 'Aucune réservation terminée',
      'No canceled bookings': 'Aucune réservation annulée',
      'No bookings': 'Aucune réservation',
      'Search Bookings': 'Rechercher des réservations',
      'Tesla (Plug)': 'Tesla (Prise)',
      'Max power': 'Puissance max',
      'Parked For': 'Stationné pendant',
      'Duration': 'Durée',
      'Total Paid': 'Total payé',
      'Amount': 'Montant',
      'Extra:': 'Supplément:',
      'Available': 'Disponible',
      'In Use': 'En cours d\'utilisation',
      'Unavailable': 'Indisponible',
      'Book Now': 'Réserver maintenant',
      'Full': 'Complet',
      'Search station': 'Rechercher une station',
      'Name': 'Nom',
      'Phone': 'Téléphone',
      'Email': 'E-mail',
      'Address': 'Adresse',
      'Date of Birth': 'Date de naissance',
      'Update': 'Mettre à jour',
      'Change Password': 'Changer le mot de passe',
      'Current Password': 'Mot de passe actuel',
      'New Password': 'Nouveau mot de passe',
      'Confirm Password': 'Confirmer le mot de passe',
      'Biometric Authentication': 'Authentification biométrique',
      'Face ID': 'Face ID',
      'Remember Me': 'Se souvenir de moi',
      'Continue with Google': 'Continuer avec Google',
      'Full Name': 'Nom complet',
      'Email Address': 'Adresse e-mail',
      'Password': 'Mot de passe',
      'Account created successfully!': 'Compte créé avec succès!',
      'Please agree to the terms and conditions':
          'Veuillez accepter les termes et conditions',
      'Let\'s you in': 'Bienvenue',
      'or': 'ou',
      'Don\'t have an account?': 'Vous n\'avez pas de compte?',
      'Already have an account?': 'Vous avez déjà un compte?',
      'Create Account': 'Créer un compte',
      'Terms and Conditions': 'Termes et conditions',
      'I agree to the': 'J\'accepte les',
      'Create your account': 'Créez votre compte',
      'Sign up to get started': 'Inscrivez-vous pour commencer',
      'Sign In': 'Se connecter',
      'No Saved Parkings': 'Aucun parking enregistré',
      'Save your favorite parking spots\nfor quick access':
          'Enregistrez vos parkings préférés\npour un accès rapide',
      'spots': 'places',
      'reviews': 'avis',
      'chargers': 'chargeurs',
      'Search Saved': 'Rechercher les enregistrés',
      'Recent Transactions': 'Transactions récentes',
      'View All': 'Voir tout',
      'No transactions yet': 'Aucune transaction pour le moment',
      'Your balance': 'Votre solde',
      'Top Up': 'Recharger',
      'RaknaGo Card': 'Carte RaknaGo',
      'This booking is already completed. Are you sure you want to cancel it?':
          'Cette réservation est déjà terminée. Êtes-vous sûr de vouloir l\'annuler?',
      'Are you sure you want to cancel this booking?':
          'Êtes-vous sûr de vouloir annuler cette réservation?',
      'Time spent:': 'Temps passé:',
      'hours': 'heures',
      '1st hour (paid):': '1ère heure (payée):',
      'Total charge:': 'Charge totale:',
      'Extra charge:': 'Charge supplémentaire:',
      'Will be deducted from wallet': 'Sera déduit du portefeuille',
      'No additional charge': 'Aucun frais supplémentaire',
      'First hour already paid (non-refundable)':
          'Première heure déjà payée (non remboursable)',
      'Yes, Cancel': 'Oui, annuler',
    },
    'es': {
      'RaknaGo': 'RaknaGo',
      // Common
      'Cancel': 'Cancelar',
      'Save': 'Guardar',
      'Delete': 'Eliminar',
      'Edit': 'Editar',
      'Confirm': 'Confirmar',
      'Yes': 'Sí',
      'No': 'No',
      'OK': 'OK',
      'Close': 'Cerrar',
      'Back': 'Atrás',
      'Next': 'Siguiente',
      'Continue': 'Continuar',
      'Done': 'Hecho',
      'Search': 'Buscar',
      'Loading': 'Cargando',
      'Error': 'Error',
      'Success': 'Éxito',
      'Warning': 'Advertencia',

      // Language Screen
      'Language': 'Idioma',
      'Suggested': 'Sugerido',
      'All Languages': 'Todos los idiomas',
      'Language changed to': 'Idioma cambiado a',
    },
    'de': {
      'RaknaGo': 'RaknaGo',
      // Common
      'Cancel': 'Abbrechen',
      'Save': 'Speichern',
      'Delete': 'Löschen',
      'Edit': 'Bearbeiten',
      'Confirm': 'Bestätigen',
      'Yes': 'Ja',
      'No': 'Nein',
      'OK': 'OK',
      'Close': 'Schließen',
      'Back': 'Zurück',
      'Next': 'Weiter',
      'Continue': 'Fortfahren',
      'Done': 'Fertig',
      'Search': 'Suchen',
      'Loading': 'Laden',
      'Error': 'Fehler',
      'Success': 'Erfolg',
      'Warning': 'Warnung',

      // Language Screen
      'Language': 'Sprache',
      'Suggested': 'Vorgeschlagen',
      'All Languages': 'Alle Sprachen',
      'Language changed to': 'Sprache geändert zu',
    },
    'it': {
      'RaknaGo': 'RaknaGo',
      // Common
      'Cancel': 'Annulla',
      'Save': 'Salva',
      'Delete': 'Elimina',
      'Edit': 'Modifica',
      'Confirm': 'Conferma',
      'Yes': 'Sì',
      'No': 'No',
      'OK': 'OK',
      'Close': 'Chiudi',
      'Back': 'Indietro',
      'Next': 'Avanti',
      'Continue': 'Continua',
      'Done': 'Fatto',
      'Search': 'Cerca',
      'Loading': 'Caricamento',
      'Error': 'Errore',
      'Success': 'Successo',
      'Warning': 'Avviso',

      // Language Screen
      'Language': 'Lingua',
      'Suggested': 'Consigliato',
      'All Languages': 'Tutte le lingue',
      'Language changed to': 'Lingua cambiata in',
    },
  };
}
